// Generated by CoffeeScript 1.10.0
(function() {
  var app, http, io;

  app = require('express')();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  app.get('/', function(req, res) {
    return res.sendFile(__dirname + '/index.html');
  });

  io.on('connection', function(socket) {
    console.log('a user connected');
    socket.on('disconnect', function() {
      return console.log('user disconnected');
    });
    return socket.on('chat message', function(msg) {
      console.log('message: ' + msg);
      return io.emit('chat message', msg);
    });
  });

  http.listen(3000, function() {
    return console.log('listening on *:3000');
  });

}).call(this);
